# Generated by Django 5.2.11 on 2026-02-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve descrição sobre o usuário.', verbose_name='Biografia'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrador'), ('school_admin', 'Administrador Escolar'), ('news_editor', 'Editor de Notícias'), ('hiring_manager', 'Gerente de Contratações')], default='news_editor', help_text='Define as permissões e acesso do usuário no sistema.', max_length=20, verbose_name='Cargo'),
        ),
    ]
