# Generated by Django 5.2.11 on 2026-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, help_text='Endereço de e-mail único. Usado para recuperação de senha.', max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
