# Generated by Django 5.2.11 on 2026-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsletter_unique_per_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Resumo curto do artigo. Aparece nas listagens e compartilhamentos.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Artigos destacados aparecem em posição de destaque na página principal.'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição para buscadores (Google). Se vazio, usa o resumo.', max_length=160),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para buscadores (Google). Se vazio, usa o título do artigo.', max_length=70),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Rascunho: não publicado. Publicado: visível no site. Arquivado: removido do site.', max_length=20),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para cancelar a inscrição deste email.'),
        ),
    ]
