# Generated by Django 5.2.11 on 2026-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_article_excerpt_alter_article_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Artigo', 'verbose_name_plural': 'Artigos'},
        ),
        migrations.AlterModelOptions(
            name='articlebookmark',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
        migrations.AlterModelOptions(
            name='articlelike',
            options={'verbose_name': 'Curtida', 'verbose_name_plural': 'Curtidas'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Assinatura de Newsletter', 'verbose_name_plural': 'Assinaturas de Newsletter'},
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', help_text='Rascunho: não publicado. Publicado: visível no site. Arquivado: removido do site.', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este comentário (moderação).'),
        ),
    ]
