# Generated by Django 5.2.11 on 2026-02-24 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_options_alter_articlebookmark_options_and_more'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text='Escolha a categoria principal do artigo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Resumo curto do artigo. Aparece nas listagens e compartilhamentos.', verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Imagem principal que aparece no topo do artigo.', upload_to='news/articles/', verbose_name='Imagem de capa'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image_caption',
            field=models.CharField(blank=True, help_text='Texto descritivo exibido abaixo da imagem de capa.', max_length=255, verbose_name='Legenda da imagem'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Artigos destacados aparecem em posição de destaque na página principal.', verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição para buscadores (Google). Se vazio, usa o resumo.', max_length=160, verbose_name='Descrição SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula. Ex: educação, escola, notícias.', max_length=255, verbose_name='Palavras-chave SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para buscadores (Google). Se vazio, usa o título do artigo.', max_length=70, verbose_name='Título SEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora da publicação. Preenchido automaticamente ao publicar.', null=True, verbose_name='Publicado em'),
        ),
        migrations.AlterField(
            model_name='article',
            name='site',
            field=models.ForeignKey(help_text='Em qual portal este artigo será publicado.', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='sites.site', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(help_text='Gerado automaticamente a partir do título.', max_length=200, unique=True, verbose_name='URL amigável'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='draft', help_text='Rascunho: não publicado. Publicado: visível no site. Arquivado: removido do site.', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Digite para buscar tags existentes.', related_name='articles', to='news.tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Visualizações'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Deixe vazio para criar uma categoria principal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.category', verbose_name='Categoria pai'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
    ]
