# Generated by Django 5.2.11 on 2026-02-24 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_article_author_alter_article_category_and_more'),
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebookmark',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='news.article', verbose_name='Artigo'),
        ),
        migrations.AlterField(
            model_name='articlebookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_articles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='articlelike',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.article', verbose_name='Artigo'),
        ),
        migrations.AlterField(
            model_name='articlelike',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Endereço IP'),
        ),
        migrations.AlterField(
            model_name='articlelike',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Chave de sessão'),
        ),
        migrations.AlterField(
            model_name='articlelike',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_likes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.article', verbose_name='Artigo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para ocultar este comentário do portal.', verbose_name='Visível'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Desmarque para cancelar a inscrição deste email.', verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='newslettersubscription',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_subscriptions', to='sites.site', verbose_name='Site'),
        ),
    ]
