# Generated by Django 5.2.11 on 2026-02-25 17:12

from django.db import migrations, models


def mark_existing_published_as_sent(apps, schema_editor):
    """
    Marca artigos publicados existentes como "newsletter já enviada"
    para evitar spam ao re-salvar artigos legados após a migration.
    Usa published_at como timestamp para preservar o audit trail.
    """
    Article = apps.get_model('news', 'Article')
    Article.objects.filter(
        status='published',
        newsletter_sent_at__isnull=True,
    ).exclude(published_at__isnull=True).update(newsletter_sent_at=models.F('published_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_articlebookmark_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='newsletter_sent_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Preenchido automaticamente quando a newsletter é enviada via sinal ou ação do admin.', null=True, verbose_name='Newsletter enviada em'),
        ),
        migrations.RunPython(
            mark_existing_published_as_sent,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
