# Generated by Django 5.2.16 on 2026-08-13 00:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_media', '0002_alter_document_options_alter_image_options'),
        ('news', '0025_align_draft_state_with_status'),
        ('sites', '0002_alter_domain_unique'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['site', 'status', '-published_at'], name='news_article_site_status_pub'),
        ),
    ]
