# Generated by Django 5.2.11 on 2026-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], default='new', help_text='Marque como Lida, Respondida ou Arquivada conforme o atendimento.', max_length=20),
        ),
    ]
