# Generated by Django 5.2.11 on 2026-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contactinquiry_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mensagem de Contato', 'verbose_name_plural': 'Mensagens de Contato'},
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'Nova'), ('read', 'Lida'), ('replied', 'Respondida'), ('archived', 'Arquivada')], default='new', help_text='Marque como Lida, Respondida ou Arquivada conforme o atendimento.', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='subject',
            field=models.CharField(choices=[('general', 'Geral'), ('admissions', 'Admissões'), ('support', 'Suporte'), ('other', 'Outro')], default='general', max_length=50),
        ),
    ]
