# Generated by Django 5.2.11 on 2026-02-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Notas internas sobre o candidato. Não visíveis ao candidato.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='received', help_text='Acompanhe o progresso desta candidatura.', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Data limite para receber candidaturas.', null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', help_text='Rascunho: não visível. Aberta: visível no site. Fechada: removida do site.', max_length=20),
        ),
    ]
