# Generated by Django 5.2.11 on 2026-02-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_alter_application_notes_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidatura', 'verbose_name_plural': 'Candidaturas'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-published_at'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('received', 'Recebida'), ('reviewing', 'Em Análise'), ('shortlisted', 'Pré-selecionada'), ('interview', 'Entrevista'), ('rejected', 'Rejeitada'), ('accepted', 'Aceita')], default='received', help_text='Acompanhe o progresso desta candidatura.', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Tempo Integral'), ('part_time', 'Meio Período'), ('contract', 'Contrato'), ('internship', 'Estágio')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('open', 'Aberta'), ('closed', 'Fechada')], default='draft', help_text='Rascunho: não visível. Aberta: visível no site. Fechada: removida do site.', max_length=20),
        ),
    ]
