# Generated by Django 5.2.11 on 2026-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_alter_application_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Descrição para buscadores (Google). Recomendado: até 160 caracteres.', max_length=160, verbose_name='Descrição SEO'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Palavras-chave separadas por vírgula. Ex: educação, escola, notícias.', max_length=255, verbose_name='Palavras-chave SEO'),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Título para buscadores (Google). Recomendado: até 70 caracteres.', max_length=70, verbose_name='Título SEO'),
        ),
    ]
