# Generated by Django 5.2.11 on 2026-02-21 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='site_logos/')),
                ('favicon', models.ImageField(blank=True, upload_to='site_favicons/')),
                ('primary_email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=30)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extension', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
