# Generated by Django 5.2.11 on 2026-02-21 17:19

from django.db import migrations


def create_default_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    SiteExtension = apps.get_model('common', 'SiteExtension')

    site, created = Site.objects.get_or_create(
        id=1,
        defaults={'domain': 'example.com', 'name': 'Kelly School e Portal de Notícias'}
    )
    if not created:
        site.name = 'Kelly School e Portal de Notícias'
        site.save()

    SiteExtension.objects.get_or_create(
        site=site,
        defaults={
            'tagline': 'Moldando o futuro, inspirando mentes.',
            'primary_email': 'contato@kellyschool.edu.br',
            'phone_number': '(11) 99999-9999',
            'address': 'Rua da Educação, 123, São Paulo - SP',
            'facebook_url': 'https://facebook.com/kellyschool',
            'instagram_url': 'https://instagram.com/kellyschool',
            'youtube_url': 'https://youtube.com/kellyschool',
        }
    )

def remove_default_site(apps, schema_editor):
    # Depending on the application lifecycle, this isn't strictly necessary, but good practice
    SiteExtension = apps.get_model('common', 'SiteExtension')
    SiteExtension.objects.filter(site__id=1).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('sites', '0001_initial'), # Important: Ensure sites framework is available
    ]

    operations = [
        migrations.RunPython(create_default_site, remove_default_site)
    ]
