# Generated by Django 5.2.11 on 2026-02-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_default_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteextension',
            options={'verbose_name': 'Configuração do Site', 'verbose_name_plural': 'Configurações dos Sites'},
        ),
    ]
