# Generated by Django 5.2.11 on 2026-02-25 15:07

import django.contrib.sites.managers
import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_page_meta_description_alter_page_meta_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='page',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
